title: Remembering Rusty

logo: site-logo-rusty.jpg

url: http://rusty.pittyfamily.net

owner:

  name:   Keith Pitty

  avatar: keith.jpg

links:
  - title: About
    url: /about
  - title: Articles
    url: /articles

timezone: Australia/Sydney

markdown: redcarpet

exclude: ["vendor"]
